### ISSUE TITLE
problems with inverse fractions of whole numbers?

### ISSUE THREAD

**Issue by lasermtv07** [ShortLang/ShortLang#7]
**Describe the bug**
Why is ***1/3!*** equal to ***0***?
I was trying to write an algorithm to calculate the Euler number, however it broke with inverse fractions ***1/n***,
always writing 0 instead of whats its supposed to *(like ***0*** instead of ***0.166666666667*** with ***3!***. Same with ***1/5***)

**To Reproduce**
run this code:
`$(1/(3!))`

**Expected behavior**
Correct calculation *(via description)*

**Screenshots**

**Desktop (please complete the following information):**
 - *OS:* Debian GNU/Linux 12 Bookworm
 - *Browser* Firefox (why does this matter?)
 - *Version* 0.1.0, patched with commented out analyzer in main.rs

**Smartphone (please complete the following information):**
***no***
**Additional context**

**Comment by lasermtv07** [comment]
works with ***1.0/n*** however it writes it in scientific notation for some reason:
`2.0000000000000001e-1`

**Comment by FirePlank** [comment]
The reason for the scientific notation is because we use the rug crate in our project for arbitrary precision arithmetic. Rug automatically prints large values with the scientific notation. The reason for stuff like 0.2 to not be 0.2 exactly is because of how computers work and store floats. I agree that `int/int=always int` isnt intented behaviour and will look to get that fixed. Thanks for the issue.

**Comment by FirePlank** [comment]
The issue has been fixed 👍

**Comment by lasermtv07** [comment]
Thanks! Have a nice day!
